import spacy
import os

# Load a pre-trained spaCy model
nlp = spacy.load("en_core_web_sm")

# Define keywords for each genre
genre_keywords_eng = {
    "action": ["explosive", "thrilling", "adrenaline-fueled", "fast-paced", "action-packed", "high-octane", "intense", "exciting", "dynamic", "dangerous", "violent", "fighting", "weapons", "stunts", "chase scenes", "shootouts", "car chases", "hand-to-hand combat", "martial arts", "spy", "espionage", "intrigue", "heroic", "vigilante", "mission", "rescue", "explosions", "gunfire", "pursuit", "special forces"],
    "comedy": ["funny", "humorous", "hilarious", "entertaining", "amusing", "lighthearted", "witty", "clever", "satirical", "parody", "spoof", "ironic", "sarcastic", "slapstick", "absurd", "goofy", "zany", "quirky", "ridiculous", "offbeat", "laugh-out-loud", "whimsical", "playful", "farce", "joke", "gag", "punchline", "comic relief", "silly", "satire"],
    "drama": ["drama", "emotional", "gripping", "tense", "suspenseful", "compelling", "heart-wrenching", "poignant", "thought-provoking", "serious", "tragic", "melodramatic", "angsty", "psychological", "dysfunctional", "powerful", "raw", "gritty", "dark", "mysterious", "complex", "moody", "atmospheric", "brooding", "authentic", "realistic", "harrowing", "cathartic", "heavy", "profound"],
    "horror": ["scary", "creepy", "terrifying", "frightening", "spine-chilling", "horrifying", "eerie", "unsettling", "disturbing", "macabre", "bloody", "gory", "haunted", "supernatural", "paranormal", "monstrous", "terrific", "dreadful", "bone-chilling", "gut-wrenching", "nail-biting", "suspenseful", "psychological", "nightmarish", "dark", "ominous", "sinister", "grim", "shadowy", "horror genre"],
    "romance": ["love", "heartwarming", "passionate", "romantic", "affectionate", "emotional", "sensual", "tender", "intimate", "sappy", "sweet", "dreamy", "sentimental", "nostalgic", "touching", "cute", "adorable", "endearing", "whimsical", "heartfelt", "bittersweet", "melancholic", "yearning", "longing", "devotion", "commitment", "flirty", "charming", "hopeful", "cheesy"],
    "science_fiction": ["futuristic", "technological", "alien", "extraterrestrial", "cybernetic", "virtual reality", "artificial intelligence", "space", "time travel", "parallel universe", "post-apocalyptic", "dystopian", "robotic", "fantastical", "speculative", "exploration", "interstellar", "cosmic", "speculation", "advanced", "innovative", "experimental", "futurism", "otherworldly", "unconventional", "fantasy", "imaginative", "scientific", "fictional", "utopian"],
    "thriller": ["suspense", "intense", "mysterious", "foreboding", "intrigue", "plot twist", "cliffhanger", "tension", "sleuthing", "mystery", "conspiracy", "perilous", "dangerous", "manipulation", "paranoia", "fear", "anxiety", "danger", "chase", "investigation", "enigma", "obsession", "surprise", "thrilling", "unpredictable", "edgy", "psychological", "cat-and-mouse", "sinister"],
    "crime": ["investigation", "police", "detective", "mystery", "murder", "forensics", "evidence", "interrogation", "witness", "confession", "robbery", "burglary", "homicide", "victim", "perpetrator", "criminal", "lawyer", "courtroom", "trial", "jury", "sentencing", "prison", "gang", "underworld", "organized crime", "drug trafficking", "smuggling", "heist", "blackmail", "corruption"],
    "documentary": ["non-fiction", "interviews", "footage", "archives", "facts", "real-life", "investigative", "exposé", "educational", "informative", "journalistic", "historical", "cultural", "political", "social", "environmental", "scientific", "human interest", "behind-the-scenes", "experts", "witnesses", "research", "analysis", "commentary", "narration", "voice-over", "perspective", "insightful", "thought-provoking", "eye-opening"],
    "Adventure": ["exploration", "quest", "journey", "dangerous", "treasure", "exotic", "far-off lands", "challenges", "action-packed", "thrilling", "exciting", "suspenseful", "mystery", "discovery", "unexpected", "survival", "epic", "fantasy", "swashbuckling", "heroes", "villains", "remote", "isolated", "courageous", "brave", "daring", "mystical", "enchanted", "magical"],
    "Animation": ["cartoon", "animated", "anime", "Pixar", "Disney", "motion graphics", "illustrations", "2D", "3D", "CGI", "motion pictures", "stop-motion", "anime series", "animated feature", "graphic novel", "character design", "animators", "animation studio", "animated TV show"],
    "Biography": ["life story", "autobiography", "memoir", "personal history", "legacy", "accomplishments", "challenges", "milestones", "struggle", "triumph", "inspiring", "motivating", "fascinating", "compelling", "revealing", "honest", "authentic", "detailed", "historical", "insightful", "impactful", "renowned", "celebrity", "innovative", "groundbreaking", "pioneering", "influential", "empowering", "educational", "documentary"],
    "Fantasy": ["fantasy", "magic", "mythical", "enchanting", "supernatural", "otherworldly", "magical creatures", "fabled", "legendary", "mystical", "wizardry", "witchcraft", "fairy tale", "epic", "whimsical", "mystical", "surreal", "imagination", "enchanted", "mysterious", "parallel universe", "futuristic", "medieval", "time-travel", "legend", "myth", "sorcery", "enchanted forest", "unreal"],
    "Musical": ["singing", "dancing", "choreography", "show tunes", "dance numbers", "music performances", "musical numbers", "ensemble cast", "song and dance", "Broadway", "dance routines", "original soundtrack", "theater", "musical theater", "melodic", "harmonious", "upbeat", "energetic", "big production numbers", "tap dance", "ballad", "vocal performances", "songwriting", "stage production", "musical comedy", "feel-good", "dance sequences", "musical performances", "orchestral arrangements", "musical interludes"],
    "Mystery": ["detective", "crime", "whodunit", "clues", "investigation", "murder", "suspense", "red herrings", "intrigue", "enigma", "unsolved", "conspiracy", "forensic", "motive", "alibi", "secret", "thriller", "puzzle", "culprit", "mystery-solving", "sleuth", "crime-solving", "plot twist", "mysterious", "evidence", "investigator", "criminal", "case", "solving the case", "solving the mystery"],
    "Psychological": ["mind games", "manipulation", "trauma", "mental health", "therapy", "emotional", "psychological thriller", "psychoanalysis", "personality disorder", "mental breakdown", "paranoia", "obsession", "delusion", "perception", "subconscious", "dissociation", "phobia", "anxiety", "depression", "psychiatrist", "psychology", "psyche", "neurosis", "hypnosis", "psychopath", "schizophrenia", "therapy session", "cognitive", "behavioral", "mental illness"],
    "Sports": ["athletes", "teams", "competition", "victory", "defeat", "scoreboard", "playoffs", "championship", "training", "coach", "strategy", "performance", "fans", "spectators", "stadium", "arena", "field", "court", "locker room", "sportsmanship", "replay", "halftime", "overtime", "commentary", "announcers", "stats", "highlights", "record", "athlete profile", "sports psychology"],
    "Superhero": ["superpowers", "costume", "secret identity", "villains", "heroic deeds", "alter ego", "origin story", "heroism", "crime-fighting", "cape", "mask", "justice", "powers and abilities", "adventure", "good versus evil", "superhuman strength", "supernatural", "mystery", "super team", "special effects", "action-packed", "saving the world", "fantasy", "superhuman speed", "superhuman agility", "comic book adaptation", "world-building", "metahuman", "avenger", "superhero origin"],
    "War": ["battle", "soldiers", "military", "weapons", "strategy", "tactics", "wartime", "conflict", "combat", "warfare", "frontline", "warzone", "casualties", "veterans", "enemy", "allies", "occupation", "resistance", "liberation", "siege", "assault", "air raid", "naval warfare", "ground troops", "war crimes", "war effort", "homefront", "propaganda", "surrender"],
    "Reality TV": ["contestants", "elimination", "drama", "conflict", "competition", "challenges", "voting", "alliances", "strategy", "backstabbing", "dynamics", "social game", "reality show", "unscripted", "docusoap", "documentary-style", "real-life", "behind-the-scenes", "camera confessionals", "dramatic music", "host", "judges", "prizes", "housemates", "villains", "protagonists", "confessional interviews", "showmance", "reality TV tropes"],
    "Romance-Comedy": ["romantic comedy", "love", "dating", "relationships", "friendship", "misunderstandings", "awkwardness", "humor", "chemistry", "flirting", "crush", "heartbreak", "happy ending", "romantic tension", "romantic gestures", "cute", "quirky", "feel-good", "rom-com", "chick flick", "soulmate", "romantic interest", "matchmaking", "confessions", "drama", "light-hearted", "laugh-out-loud", "romantic rivalry", "romantic escapades", "unrequited love"]}
    # add more genres and keywords as needed
genre_keywords_fr = {
"action": ["explosif", "palpitant", "sous haute tension", "rythmé", "rempli d'action", "à haut risque", "intense", "excitant", "dynamique", "dangereux", "violent", "combats", "armes", "cascades", "scènes de poursuite", "fusillades", "courses-poursuites en voiture", "combats à mains nues", "arts martiaux", "espionnage", "intrigues", "héroïque", "justicier", "mission", "sauvetage", "explosions", "coups de feu", "poursuite", "forces spéciales"],
"comedy": ["drôle", "humoristique", "hilare", "divertissant", "amusant", "léger", "spirituel", "intelligent", "satirique", "parodie", "parodie", "ironique", "sarcastique", "burlesque", "absurde", "farfelu", "dingue", "bizarre", "ridicule", "décalé", "à mourir de rire", "fantaisiste", "joueur", "farce", "blague", "gag", "pointe", "comique de situation", "silly", "satire"],
"drama": ["drame", "émotionnel", "captivant", "tendu", "suspense", "convaincant", "déchirant", "évocateur", "stimulant", "sérieux", "tragique", "mélodramatique", "angoissant", "psychologique", "dysfonctionnel", "puissant", "cru", "rugueux", "sombre", "mystérieux", "complexe", "maussade", "atmosphérique", "pensif", "authentique", "réaliste", "éprouvant", "cathartique", "intense", "profond"],
"horror": ["effrayant", "inquiétant", "terrifiant", "effrayant", "chair de poule", "horrible", "étrange", "perturbant", "macabre", "sanglant", "gore", "hanté", "surnaturel", "paranormal", "monstrueux", "terrifiant", "redoutable", "horrible", "qui fait froid dans le dos", "qui retourne les tripes", "à couper le souffle", "sous haute tension", "psychologique", "cauchemardesque", "sombre", "menaçant", "sinistre", "sévère", "ombreux", "genre d'horreur"],
"romance": ["amour", "réconfortant", "passionné", "romantique", "affectueux", "émotionnel", "sensuel", "tendre", "intime", "gnangnan", "mignon", "rêveur", "sentimental", "nostalgique", "émouvant", "mignon", "adorable", "attachant", "fantaisiste", "sincère", "aigre-doux", "mélancolique", "aspirant", "désirant", "dévouement", "engagement", "flirtant", "charmante", "pleine d'espoir", "ringarde"],
"science_fiction": ["futuriste", "technologique", "extraterrestre", "cybernétique", "réalité virtuelle", "intelligence artificielle", "espace", "voyage dans le temps", "univers parallèle", "post-apocalyptique", "dystopique", "robotique", "fantastique", "spéculatif", "exploration", "interstellaire", "cosmique", "spéculation", "avancé", "innovant", "expérimental", "futurisme", "autre-monde", "non conventionnel", "fantaisie", "imaginatif", "scientifique", "fictionnel", "utopique"],
"thriller": ["suspens", "intense", "mystérieux", "prémonitoire", "intrigue", "rebondissement", "cliffhanger", "tension", "détective", "mystère", "complot", "périlleux", "dangereux", "manipulation", "paranoïa", "peur", "anxiété", "danger", "chasse", "enquête", "énigme", "obsession", "surprise", "passionnant", "imprévisible", "nerveux", "psychologique", "chat et souris", "sinistre"],
"crime": ["enquête", "police", "détective", "mystère", "meurtre", "médecine légale", "preuves", "interrogatoire", "témoin", "aveu", "cambriolage", "effraction", "homicide", "victime", "auteur", "criminel", "avocat", "salle d'audience", "procès", "jury", "condamnation", "prison", "gang", "monde souterrain", "crime organisé", "trafic de drogue", "contrebande", "casse", "chantage", "corruption"],
"documentary": ["non-fiction", "interviews", "footage", "archives", "faits", "réel", "d'enquête", "exposé", "éducatif", "informatif", "journalistique", "historique", "culturel", "politique", "social", "environnemental", "scientifique", "intérêt humain", "coulisses", "experts", "témoins", "recherche", "analyse", "commentaire", "narration", "voix off", "perspective", "perspicace", "stimulant", "éclairant"],
"Adventure": ["exploration", "quête", "voyage", "dangereux", "trésor", "exotique", "terres lointaines", "défis", "pleine d'action", "palpitant", "excitant", "suspense", "mystère", "découverte", "inattendu", "survie", "épique", "fantastique", "chevaleresque", "héros", "villains", "isolé", "courageux", "brave", "audacieux", "mystique", "enchanté", "magique"],
"animation": ["dessin animé", "animé", "anime", "Pixar", "Disney", "graphisme animé", "illustrations", "2D", "3D", "CGI", "films d'animation", "stop-motion", "série anime", "film d'animation", "roman graphique", "design de personnages", "animateurs", "studio d'animation", "série animée"],
"Biography": ["histoire de vie", "autobiographie", "mémoire", "histoire personnelle", "héritage", "réalisations", "défis", "jalons", "lutte", "triomphe", "inspirant", "motivant", "fascinant", "captivant", "révélateur", "honnête", "authentique", "détaillé", "historique", "perspicace", "impactant", "renommé", "célébrité", "innovant", "révolutionnaire", "pionnier", "influent", "habilitant", "éducatif", "documentaire"],
"Fantasy": ["fantaisie", "magie", "mythique", "enivrant", "surnaturel", "d'autre monde", "créatures magiques", "fabuleux", "légendaire", "mystique", "sorcellerie", "conte de fée", "épique", "capricieux", "mystérieux", "surréaliste", "imagination", "enchanté", "parallèle", "futuriste", "médiéval", "voyage dans le temps", "légende", "mythe", "sorcellerie", "forêt enchantée", "irréel"],
"Musical": ["chant", "danse", "numéro musical", "comédie musicale", "chorégraphie", "spectacle musical", "interprète", "paroles de chansons", "numéro de danse", "comédie musicale classique", "performance en direct", "instrument de musique", "opéra", "opérette", "soliste", "ensemble vocal", "ballade", "reprise", "rhythm and blues", "jazz", "blues", "rock and roll", "pop", "country", "folk", "hip hop", "rap", "techno", "disco"],
"Mystery": ["énigme", "intrigue", "énigmatique", "énigme résolue", "enquêteur", "suspect", "alibi", "policier", "détective", "poursuite", "crime", "meurtre", "indice", "piste", "témoin", "victime", "disparition", "énigme non résolue", "suspense", "rebondissement", "thriller", "criminel", "évasion", "coupable", "poursuite", "preuve", "faux-semblant", "histoire vraie", "découverte", "étrange"],
"Psychological": ["jeux mentaux", "manipulation", "traumatisme", "santé mentale", "thérapie", "émotionnel", "thriller psychologique", "psychanalyse", "trouble de la personnalité", "crise de nerfs", "paranoïa", "obsession", "délire", "perception", "subconscient", "dissociation", "phobie", "anxiété", "dépression", "psychiatre", "psychologie", "psyché", "névrose", "hypnose", "psychopathe", "schizophrénie", "séance de thérapie", "cognitif", "comportemental", "maladie mentale"],
"Sports": ["athlètes", "équipes", "compétition", "victoire", "défaite", "tableau des scores", "playoffs", "championnat", "entraînement", "entraîneur", "stratégie", "performance", "fans", "spectateurs", "stade", "arène", "terrain", "court", "vestiaire", "fair-play", "replay", "mi-temps", "prolongation", "commentaire", "commentateurs", "statistiques", "moments forts", "record", "profil de l'athlète", "psychologie du sport"],
"Superhero": ["superpowers", "costume", "secret identity", "villains", "heroic deeds", "alter ego", "origin story", "heroism", "crime-fighting", "cape", "mask", "justice", "powers and abilities", "adventure", "good versus evil", "superhuman strength", "supernatural", "mystery", "super team", "special effects", "action-packed", "saving the world", "fantasy", "superhuman speed", "superhuman agility", "comic book adaptation", "world-building", "metahuman", "avenger", "superhero origin"],
"War": ["bataille", "soldats", "militaire", "armes", "stratégie", "tactique", "temps de guerre", "conflit", "combat", "guerre", "ligne de front", "zone de guerre", "pertes", "vétérans", "ennemi", "alliés", "occupation", "résistance", "libération", "siège", "assaut", "raid aérien", "guerre navale", "troupes au sol", "crimes de guerre", "effort de guerre", "arrière-front", "propagande", "reddition"],
"Reality TV": ["candidats", "élimination", "drame", "conflit", "compétition", "défis", "votations", "alliances", "stratégie", "coups bas", "dynamiques", "jeu social", "émission de téléréalité", "non-scripté", "docu-série", "style documentaire", "réalité", "coulisses", "confessions devant la caméra", "musique dramatique", "animateur", "juges", "prix", "colocataires", "antagonistes", "protagonistes", "interviews confessionnelles", "idylle à l'écran", "tropes de la téléréalité"],
"Romance-Comedy": ["Comédie romantique", "amour", "rendez-vous", "relations amoureuses", "amitié", "malentendus", "gêne", "humour", "alchimie", "flirt", "béguin", "chagrin d'amour", "fin heureuse", "tension romantique", "gestes romantiques", "mignon", "excentrique", "sentiment de bien-être", "rom-com", "film de filles", "âme sœur", "intérêt romantique", "entremetteur", "aveux", "drame", "léger", "drôle", "rivalité romantique", "aventures romantiques", "amour non partagé"]}

# add more genres and keywords as needed
# Define a function to classify a subtitle file based on its content
def classify_subtitle_file(file_path):
    with open(file_path, "r") as file:
        text = file.read()
    doc = nlp(text)
    
    if any(word in doc.text.lower() for word in ["for", "and", "the", "from", "to"]):
        genre_keywords = genre_keywords_eng
    else:
        genre_keywords = genre_keywords_fr
    
    max_score = 0
    max_genre = "unknown"
    for genre, keywords in genre_keywords.items():
        score = sum(keyword in doc.text.lower() for keyword in keywords)
        if score > max_score:
            max_score = score
            max_genre = genre
    return max_genre

# Traverse all files in the directory and classify each subtitle file
directory_path = "C:/wamp64/www/asmr/TEST SUBS/90210"
genre_count = {}

for filename in os.listdir(directory_path):
    if filename.endswith(".txt"):
        file_path = os.path.join(directory_path, filename)
        genre = classify_subtitle_file(file_path)
        if genre in genre_count:
            genre_count[genre] += 1
        else:
            genre_count[genre] = 1
        print(f"{filename}: {genre}")

top_genres = sorted(genre_count, key=genre_count.get, reverse=True)[:5]

print("The top genres in these subtitle files are:")
for genre in top_genres:
    print(f"{genre}: {genre_count[genre]}")

